### ISSUE TITLE
Sizle - Front-end

### ISSUE THREAD

**Issue by christoga** [GitIndonesia/awesome-indonesia-repo#2]
The repo : https://github.com/christoga/sizle
The demo : http://christo.js.org/sizle/

Category: Front-end
Useful for: scale size

Can this be on the repo list?
I create this tool to make my job more easier. :smile:

**Comment by dikiaap** [comment]
what are you using for?
looks like a little. please look sample of projects on this list.

this repo name is awesome and certainly a lot of people using it.

**Comment by christoga** [comment]
I use it to scale image size,
Div size and other things.

Maybe it will go into **Front-end Development** repo list.

**Comment by dikiaap** [comment]
Yeah, but you can make big projects and many people use your project. Its cool and this repo not started for promotion :)
http://contributor-covenant.org
Look http://ibacor.com - https://github.com/bachors He also from indonesia and make great stuff

And don't thumb for starting discuss, it's weird.

**Comment by dikiaap** [comment]
Now you child and can make it like this, I think in the future you can make great things. :+1:

**Comment by christoga** [comment]
I was only testing dude :grin:

**Comment by christoga** [comment]
I will change the desc in the readme, thank dude :smile:

**Comment by dikiaap** [comment]
Ok, nope. :smile:

**Comment by wicky-info** [comment]
greatt

**Comment by dikiaap** [comment]
Ya @wicky-info . Dia masih smp. Dan ngoding nya lumayan. Hahaha

**Comment by christoga** [comment]
Thanks dude :smile: :sunglasses: @dikiaap

**Comment by wicky-info** [comment]
wow ...kereeen broo ..sukses !!
