### ISSUE TITLE
Add repository explore-github

### ISSUE THREAD

**Issue by mazipan** [GitIndonesia/awesome-indonesia-repo#49]
Bolehkah​ ditambahkan repository explore-github.
Tambahkan ke list VueJs.

Link : https://github.com/mazipan/explore-github
Demo : https://mazipan.github.io/explore-github/

Terima Kasih kalau berkenan 😀

**Comment by dikiaap** [comment]
@mazipan Bagus. Silahkan buat PR saja om.
Walaupun ada beberapa bug, bisa untuk bahan belajar bagi pengguna Vue yang lainnya.

Saya beritahu saja bug nya disini ya:
- Search profile yang harus direfresh, sebelumnya lewat fitur search cuma current profile.
- Ada pilihan following dan followers di Organisasi.

**Comment by zhiephie** [comment]
Added https://github.com/GitIndonesia/awesome-indonesia-repo/commit/23eeaf3a18f668bdf575dd2ab94114adbbd3f60d

**Comment by mazipan** [comment]
Thanks, maaf weekend gak bisa PR.
