### ISSUE TITLE
Tambah HTMLy ke CMS/PHP

### ISSUE THREAD

**Issue by indrakaw** [GitIndonesia/awesome-indonesia-repo#5]
Summary:
>[HTMLy](https://github.com/danpros/htmly) is an open source Databaseless Blogging Platform or Flat-File Blog prioritizes simplicity and speed written in PHP. HTMLy can be referred to as Flat-File CMS either since it will also manage your content.

Main contributor: **danpros**

CMS ini popular, karena databaseless dan conten panel yang kaya. Ukurannya juga kecil.

Perlu ditambah ke repo?

**Comment by dikiaap** [comment]
@indrakaw Sep, silahkan buat PR.
